#!/bin/bash

#Define Color Code
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

#Create directory to check statuslog
if [ ! -d /opt/statuslog/ ] || [ ! -d /opt/statuslog/monitor ]; then
	mkdir -p /opt/statuslog/
	mkdir /opt/statuslog/monitor
fi

#Parameter
namaService=$1
running=$(echo -e "${GREEN}running${NC}")
notFound=$(echo -e "${RED}Not-Found${NC}")
notWorked=$(echo -e "${RED}Down${NC}")
pathCheck=/opt/statuslog/monitor/dataService

#Function
checkservice () {
	while read namaService; do
		# Output service status in File
		service $namaService status &> /opt/statuslog/$namaService.log

		# Parsing string to check service
		# Parsing "Active" word
		parActive=$(cat /opt/statuslog/$namaService.log | grep Active | awk '{ print $2 }' | cut -f 2,1 -d '(' --output-delimiter='' | cut -f 2,1 -d ')' --output-delimiter='')
		# Parsing "Running" word
		parRunning=$(grep -c "running" /opt/statuslog/$namaService.log)
		# Parsing "notbefound" word
		parNoservice=$(cat /opt/statuslog/$namaService.log | grep Unit | awk '{ print $4 $5 $6 }' | cut -f 1 -d '.' --output-delimiter='')
	    
		# Check Services
		if [[ $parActive == active ]] || [[ $parRunning -gt 0 ]] ; then
			printf "%02s\t\t\t%02s\t\t\t\t%02s\n" $namaService $running $(cat /opt/statuslog/$namaService.log | grep Active | awk '{ print $9 }')
			rm -rf  /opt/statuslog/$namaService.log
		elif [[ $parNoservice == notbefound ]]; then
			printf "%02s\t\t\t%02s\t\t\t\t%02s\n" $namaService $notFound -
		else
			printf "%02s\t\t\t%02s\t\t\t\t%02s\n" $namaService $notWorked -
       		fi
	done < $pathCheck
}

if [ $1 == all ]; then
	printf "%02s\t\t\t%02s\t\t\t\t%02s\n" Service Status Uptimie
	checkservice
elif [ $1 == add ]; then
	touch /opt/statuslog/monitor/dataService
	if grep -Fxq "$2" /opt/statuslog/monitor/dataService; then
		echo "Service telah ada"
	else
		echo "$2" >> /opt/statuslog/monitor/dataService
	fi
elif [ $1 == del ]; then
	sed -i "/$2/d" /opt/statuslog/monitor/service.data
else
	printf "%02s\t\t\t%02s\t\t\t\t%02s\n" Service Status Uptimie
	echo "$1" > /opt/statuslog/monitor/Service
	pathCheck=/opt/statuslog/monitor/Service
	checkservice	
	rm -rf /opt/statuslog/monitor/Service
fi

